/**
 * Helper script to automatically generate .env.local for all 6 dashboards
 * and proxy/.env with zero manual typing.
 *
 * Usage:
 *   node scripts/setup-env.js                           (defaults to http://localhost:2026)
 *   node scripts/setup-env.js http://YOUR_VPS_IP:2026  (for VPS deployment)
 *   node scripts/setup-env.js https://api.domain.com   (for Custom Domain)
 */

const fs = require('fs');
const path = require('path');

const targetApiUrl = process.argv[2] || 'http://localhost:2026';
const anonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpweXR4bW54Ymljam1nc2dwcmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2ODk1NzAsImV4cCI6MjA4ODI2NTU3MH0.BGQGztExtjrTr6XHrvQZ1A0njAAdkoBAp3APRfWsQNE';

const appDirs = [
  'apps/transparansi-anggaran/apps/web-next',
  'apps/dashboard-kementerian',
  'apps/dashboard-bank',
  'apps/dashboard-auditor',
  'apps/dashboard-institusi-pendidikan',
  'apps/dashboard-apbd'
];

console.log('==================================================================');
console.log(' 🛠️  AUTOMATIC ENVIRONMENT SETUP (.env.local Generator)');
console.log('==================================================================');
console.log(` Target API Proxy URL: ${targetApiUrl}\n`);

const envContent = `# Auto-generated by setup-env.js for 100% Local PostgreSQL Proxy (Port 2026)
# NO SUPABASE CLOUD ACCOUNT NEEDED - 100% SELF-HOSTED
NEXT_PUBLIC_SUPABASE_URL=${targetApiUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
`;

appDirs.forEach(dir => {
  const fullDir = path.join(__dirname, '..', dir);
  if (fs.existsSync(fullDir)) {
    const envFile = path.join(fullDir, '.env.local');
    fs.writeFileSync(envFile, envContent, 'utf8');
    console.log(` ✅ Created: ${dir}/.env.local`);
  } else {
    console.warn(` ⚠️  Directory not found: ${dir}`);
  }
});

// Setup proxy/.env
const proxyEnvContent = `# PostgreSQL Connection for Local Proxy API
DATABASE_URL=postgresql://postgres:postgres@localhost:2025/postgres
PORT=2026
`;
const proxyDir = path.join(__dirname, '..', 'proxy');
if (fs.existsSync(proxyDir)) {
  fs.writeFileSync(path.join(proxyDir, '.env'), proxyEnvContent, 'utf8');
  console.log(` ✅ Created: proxy/.env`);
}

console.log('\n🎉 ALL .env.local FILES CONFIGURED SUCCESSFULLY!');
console.log('==================================================================');
